### ISSUE TITLE
Error: attempt to index a nil value

### ISSUE THREAD

**Issue by drumsta** [ivanwfr/GQSB#1]
From time to time this error appears at the time when you log in the character.

![greymindquickslotbarerror](https://cloud.githubusercontent.com/assets/1282771/8021904/fd29b2b0-0caa-11e5-9e2c-593ffd29ca07.PNG)

**Comment by ivanwfr** [comment]
Thanks for this screenshot,

I've already been warned about this error I've never seen myself on my 
own rig. I have corrected it with w pre-released version on GitHub with 
linked there:
http://www.esoui.com/downloads/fileinfo.php?id=258#comments

Your mail decided me to push release v2.1.9 today.

Have a good time in ESO,
Ivan

**Comment by drumsta** [comment]
Hi Ivan,

I'm programmer too, so I know that screenshots help a lot! :)

Best regards and safe journey in ESO!
Arturas
